# CMake generated Testfile for 
# Source directory: /home/srushti/workarea/uhd/host/tests
# Build directory: /home/srushti/workarea/uhd/host/examples/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(addr_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/addr_test_test.sh")
add_test(buffer_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/buffer_test_test.sh")
add_test(byteswap_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/byteswap_test_test.sh")
add_test(cast_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/cast_test_test.sh")
add_test(chdr_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/chdr_test_test.sh")
add_test(constrained_device_args_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/constrained_device_args_test_test.sh")
add_test(convert_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/convert_test_test.sh")
add_test(dict_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/dict_test_test.sh")
add_test(eeprom_utils_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/eeprom_utils_test_test.sh")
add_test(error_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/error_test_test.sh")
add_test(fp_compare_delta_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/fp_compare_delta_test_test.sh")
add_test(fp_compare_epsilon_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/fp_compare_epsilon_test_test.sh")
add_test(gain_group_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/gain_group_test_test.sh")
add_test(isatty_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/isatty_test_test.sh")
add_test(log_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/log_test_test.sh")
add_test(math_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/math_test_test.sh")
add_test(narrow_cast_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/narrow_cast_test_test.sh")
add_test(property_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/property_test_test.sh")
add_test(ranges_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/ranges_test_test.sh")
add_test(scope_exit_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/scope_exit_test_test.sh")
add_test(sid_t_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/sid_t_test_test.sh")
add_test(sensors_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/sensors_test_test.sh")
add_test(soft_reg_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/soft_reg_test_test.sh")
add_test(sph_recv_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/sph_recv_test_test.sh")
add_test(sph_send_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/sph_send_test_test.sh")
add_test(subdev_spec_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/subdev_spec_test_test.sh")
add_test(time_spec_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/time_spec_test_test.sh")
add_test(tasks_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/tasks_test_test.sh")
add_test(vrt_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/vrt_test_test.sh")
add_test(expert_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/expert_test_test.sh")
add_test(fe_conn_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/fe_conn_test_test.sh")
add_test(block_id_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/block_id_test_test.sh")
add_test(blockdef_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/blockdef_test_test.sh")
add_test(device3_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/device3_test_test.sh")
add_test(graph_search_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/graph_search_test_test.sh")
add_test(node_connect_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/node_connect_test_test.sh")
add_test(rate_node_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/rate_node_test_test.sh")
add_test(stream_sig_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/stream_sig_test_test.sh")
add_test(tick_node_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/tick_node_test_test.sh")
add_test(eeprom_c_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/eeprom_c_test_test.sh")
add_test(error_c_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/error_c_test_test.sh")
add_test(ranges_c_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/ranges_c_test_test.sh")
add_test(sensors_c_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/sensors_c_test_test.sh")
add_test(string_vector_c_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/string_vector_c_test_test.sh")
add_test(subdev_spec_c_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/subdev_spec_c_test_test.sh")
add_test(nocscript_expr_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/nocscript_expr_test_test.sh")
add_test(nocscript_ftable_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/nocscript_ftable_test_test.sh")
add_test(nocscript_parser_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/nocscript_parser_test_test.sh")
add_test(config_parser_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/config_parser_test_test.sh")
add_test(paths_test "/bin/sh" "/home/srushti/workarea/uhd/host/examples/tests/paths_test_test.sh")
subdirs("common")
subdirs("devtest")
